### ISSUE TITLE
Suggestion: Add optional 'example usage' string that gets printed out below the description of a component in config yaml

### ISSUE THREAD

**Issue by BlackDragonBE** [viash-io/viash#53] opened 2021-05-13 11:37 UTC
For example, take this yaml:

```yaml
functionality:
  name: hello_world
  description: A very simple 'Hello world' component.
  example: visitor. --greeter="Greetings"
  arguments:
  - type: string
    name: input
    multiple: true
    multiple_sep: " "
  - type: string
    name: --greeter
    default: "Hello world!"
  resources:
  - type: bash_script
    path: script.sh
  tests:
  - type: bash_script
    path: test.sh
platforms:
  - type: native
  - type: docker
    image: bash:4.0
  - type: docker
    id: alpine
    image: alpine
    setup:
      - type: apk
        packages: [ bash ]
```

If you'd run `viash run config.vsh.yaml -- --help` on this, this might be the possible output:  
   
```
A very simple 'Hello world' component.
Example usage:
viash run config.vsh.yaml -- visitor. --greeter="Greetings"

Options:
    string1 string2 ...
        type: string, multiple values allowed

    --greeter=string
        type: string, default: Hello world!
```

In a nutshell, it adds an example by adding `viash run config.vsh.yaml --` before the example defined in yaml.

**Comment by rcannood** [comment] 2021-05-18 00:21
Interesting. Nothing is stopping users from currently doing this already using the description field, but it might be nice to have a separate field for this. 

We could also add an 'example' field to each of the arguments.

@tverbeiren what do you think? `.functionality.example`? `.functionality.arguments[].example`?

(An argument example might be useful for Nextflow too...)

**Comment by tverbeiren** [comment] 2021-05-18 09:34
> @tverbeiren what do you think? `.functionality.example`? `.functionality.arguments[].example`?

+1

**Comment by rcannood** [comment] 2021-05-27 10:42
Duplicate of #56.

**Closed by rcannood** 2021-05-27 10:42 UTC
Labels: enhancement
